server:
  port: 2020

spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://192.168.0.105/mydb?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: chenBIAO1!
    test2:
      jdbc-url: jdbc:mysql://192.168.0.105/mydb?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root

mybatis:
  mapper-locations: classpath*:/mapper/**.xml